version: '3'
services:

  db:
    image: postgres:17.0
    container_name: order-service-db
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=integrationTestsDB

  rabbitMQ:
    image: rabbitmq:management
    container_name: order-service-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_LOAD_DEFINITIONS: /etc/rabbitmq/definitions.json
