services:

  order-service:
    image: gradle:8.7-jdk21
    container_name: order-service
    working_dir: /home/gradle
    volumes:
      - ./src:/home/gradle/src
      - ./build.gradle:/home/gradle/build.gradle
      - ./build:/home/gradle/build  # Mount the build directory for reports
      - gradle_cache:/home/gradle/.gradle # Cache Gradle dependencies
    environment:
      - JDBC_DATABASE_URL=jdbc:postgresql://db:5432/integrationTestsDB
      - JDBC_DATABASE_USERNAME=dbuser
      - JDBC_DATABASE_PASSWORD=dbpassword
      - RABBITMQ_HOST=rabbitMQ
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - db
      - rabbitMQ

  db:
    image: postgres:17.0
    container_name: order-service-db
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=integrationTestsDB

  rabbitMQ:
    image: rabbitmq:management
    container_name: order-service-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_LOAD_DEFINITIONS: /etc/rabbitmq/definitions.json

volumes:
  gradle_cache:
