#TODO Review file
#TODO Remove REGISTRY_URL from file

version: '3'
services:
#  integration-tests:
#    container_name: integration-tests
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    volumes:
#      # Add caching
#      - gradle_user_home:/gradle_user_home
#      # Gradle cache
#      - ./.gradle:/app/.gradle
#      # build cache
#      - ./build:/app/build
#      # Add git to docker, so we can access the tags for use in gradle versioning
#      - ./.git:/app/.git
#      # App sources
#      - ./src:/app/src
#      - ./build.gradle:/app/build.gradle
#      - ./gradle.properties:/app/gradle.properties
#      - ./settings.gradle:/app/settings.gradle
#      - ./config:/app/config
#    environment:
#      - JDBC_DATABASE_URL=jdbc:postgresql://db:5432/integrationTestsDB
#      - JDBC_DATABASE_USERNAME=dbuser
#      - JDBC_DATABASE_PASSWORD=dbpassword
#      - GRADLE_USER_HOME=/gradle_user_home
#      - SPRING_PROFILES_ACTIVE
#      - RABBIT_HOSTNAME=amqp://rabbitmq
#    depends_on:
#      - db
##      - rabbitmq

#  rabbitmq:
#    container_name: rabbitmq
#    image: ${REGISTRY_URL}rabbitmq:3.8.22-management
#    ports:
#      - "5672:5672"
#      - "15672:15672"

  db:
    image: postgres:17.0
    container_name: integration-tests-db
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=integrationTestsDB

#volumes:
#  gradle_user_home:
#  postgres_data:
